version: "3.9"

services:
  backend:
    build: ./IMCUFIDE
    container_name: imcufide-backend
    ports:
      - "8000:8000"
    volumes:
      - ./IMCUFIDE:/app
    restart: unless-stopped

  frontend:
    build: ./imcufide-frontend
    container_name: imcufide-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
